nix: add shell.nix file
invoke-ai/InvokeAI pull request #1170
Opened 2022-10-19 19:15 UTC by Cloudef

Provides way to get InvokeAI environment through nix [1]
This merely wraps miniconda into a own shell environment, and does not try to reproduce the build itself.
Tested on both linux-x86_64 and aarch64-darwin

1: https://nixos.org/

2022-10-20 19:27 UTC, colemickens commented
Oh hey there @Cloudef. I'm sorta only willing to put time into this at rare moments, but I have a flake that actually can run invoke-ai already :D

If you wanted to help me get the last bits packaged, I'd love to be able to point to an ACTUALLY EASY TO RUN stable-diffusion fork.

2022-10-20 19:28 UTC, colemickens commented
I guess linking to it would help: https://github.com/colemickens/stable-diffusion-flake

2022-10-20 19:29 UTC, colemickens commented
(note that the flake's shell still uses `pip` for the last few packages, but it beats the pants off using miniconda imo)

2022-10-20 20:16 UTC, Cloudef commented
@colemickens hey that actually looks really neat. By the way have you considered trying out https://github.com/DavHau/mach-nix ?

2022-10-20 20:38 UTC, colemickens commented
whoa, no, I hadn't even come across that. It looks neat, seems like there's more and more efforts like this popping up for various languages.

(Sidenote, just opportunistically, @Cloudef, NixCon is going on this week in Paris and there's a hackathon on Saturday. If you want to collaborate on this, I think it'd be fun and I think our TZs overlap a bit. There's lots of discussion here about how to "market" Nix, and goodness, this feels like a good opportunity. I'm on matrix as `@colemickens:matrix.org` if you want to ping me and find/make a room to collab.)

2022-10-21 07:52 UTC, colemickens commented
Here, it's busted right now but I'm going to be working on it here:
https://github.com/colemickens/InvokeAI/tree/flake

1. Need to package a couple more python bits.
2. InvokeAI really needs to support loading the model file from outside the repo or something.

2022-10-21 09:25 UTC, colemickens commented
So, I have a version that works with `nix run`! It's still hacky, but I'm pretty darn pleased already.

2022-10-21 10:48 UTC, lstein requested changes
This is great. My only request is that you change the PR to rebase it against `development`. Thanks.

2022-10-23 00:17 UTC, Cloudef commented
Done

2022-10-25 11:08 UTC, lstein approved these changes
LGTM

2022-10-25 11:08 UTC, merged