Add Model Scanning
invoke-ai/InvokeAI pull request #1495
Opened 2022-11-16 09:36 UTC by blessedcoolant

Uses the [picklescan](https://github.com/mmaitre314/picklescan) library to scan the models that are being loaded to InvokeAI.

If the model is infected in anyway, the app shuts down immediately and the user is warned. If the model is unable to be scanned, then the user is presented with options to either continue or exit.

2022-11-16 16:52 UTC, tildebyte commented on installer/requirements.in
> +picklescan==0.0.5
We shouldn't pin this in here (let pip-compile figure it out), UNLESS there's some hard requirement to do so

2022-11-16 16:54 UTC, tildebyte commented on ldm/invoke/model_cache.py
> +        from picklescan.scanner import scan_file_path
Can these imports move to the top of this file?

2022-11-16 17:03 UTC, tildebyte commented on ldm/invoke/model_cache.py
> +        import sys
Can these imports move to the top of this file?

2022-11-17 00:54 UTC, tildebyte commented
LGTM, but I'll wait for@lstein to test this out and ACK or not

2022-11-17 03:36 UTC, lstein requested changes
I think we need changes to the environments files as well.

2022-11-17 03:42 UTC, blessedcoolant commented
> I think we need changes to the environments files as well.

Done.

2022-11-17 04:01 UTC, lstein commented
Tested this out on Linux. It didn't crash, the scan was fast, and reported OK. Have you tested a corrupted or malicious .ckpt file and know that the scanner will catch problems?

Please update requirements in the environments files, and this is good to go, I think.

2022-11-17 04:02 UTC, lstein approved these changes
Looking good.

2022-11-17 04:02 UTC, merged

2022-11-17 04:04 UTC, blessedcoolant commented
> Tested this out on Linux. It didn't crash, the scan was fast, and reported OK. Have you tested a corrupted or malicious .ckpt file and know that the scanner will catch problems?

I haven't tested it with a corrupt file coz I didn't know where to find one. However the library seems to be popular and well made. @tildebyte might have tested / heard of it working correctly.

I had a look at the library itself. It basically looks for any eval calls -- which is how most malicious code would be executed. As long as it does that effectively, I think this'll do the job.

From our end, this is not meant to be a hardcore safety check but another line of defense that will help users. Which I feel it does.

2022-11-21 13:37 UTC, McPatate commented
Hey, thanks for using picklescan !

Imho it should cover your needs for the moment. We use it on the hugging face hub to get the imports list you see in our 'Files and versions' tab.

You can see an example of malicious pickle [here](https://huggingface.co/ykilcher/totally-harmless-model/tree/main).

2022-11-21 13:48 UTC, blessedcoolant commented
> Hey, thanks for using picklescan !
> 
> Imho it should cover your needs for the moment. We use it on the hugging face hub to get the imports list you see in our 'Files and versions' tab.
> 
> You can see an example of malicious pickle [here](https://huggingface.co/ykilcher/totally-harmless-model/tree/main).

Hey, thanks for reaching out. Yeah, it seems like it'll get the job done. And it is inactive development so I think we should be set for a while into the future too.