Non-interactive model download + initfile location
invoke-ai/InvokeAI pull request #1578
Opened 2022-11-27 11:04 UTC by ebr

(WIP) Fixes #1559

2022-11-27 16:43 UTC, keturn commented
[`huggingface_hub.login(token)`](https://huggingface.co/docs/huggingface_hub/package_reference/login#huggingface_hub.login) could be a more-explicit alternative to resetting `os.environ` inside the script.

Also note that they've changed the settings on some of the repos so now not _all_ of the Stable Diffusion models require a token. As of last time I checked earlier this weekend, the `CompVis/` ones don't (SD 1.4) but the `runwayml/` ones do (SD 1.5 + SD 1.5 inpainting).

2022-11-27 18:58 UTC, ebr commented
> [`huggingface_hub.login(token)`](https://huggingface.co/docs/huggingface_hub/package_reference/login#huggingface_hub.login) could be a more-explicit alternative to resetting `os.environ` inside the script.

That is how I initially implemented it, but the behaviour becomes inconsistent between using the officially supported env var `HUGGINGFACE_HUB_TOKEN`. and the de-facto "community standard" `HUGGINGFACE_TOKEN`. Calling the `.login()` method causes the token to be saved in `~/.huggingface/token`, whereas using the official env. var does not.

2022-11-27 22:23 UTC, ebr commented
Moving the initialization file is proving tricky if we want to maintain backwards compatibility with the current setup, because we want to move it into the runtime dir, but users might already have a conflicting `--root-dir` argument  in an existing `~/.invokeai` file. Also, setting it from `Globals` before checking for a user-specified runtime dir creates a catch-22. 

TLDR; Perhaps the initfile should be dealt with in a separate PR so that this one isn't blocked for too long. Unless we decide to break backwards-compatibility, then it's easy

2022-11-28 02:41 UTC, lstein commented
> Moving the initialization file is proving tricky if we want to maintain backwards compatibility with the current setup, because we want to move it into the runtime dir, but users might already have a conflicting `--root-dir` argument in an existing `~/.invokeai` file. Also, setting it from `Globals` before checking for a user-specified runtime dir creates a catch-22.
> 
> TLDR; Perhaps the initfile should be dealt with in a separate PR so that this one isn't blocked for too long. Unless we decide to break backwards-compatibility, then it's easy

Why not have an environment variable that contains the path to the init file?

As an aside, introducing Globals wasn't my favorite approach, but it was better than carrying a directory path across multiple nested functions.

Just to set expectations, unless the release gets delayed significantly I'm going to go with the existing configuration script for 2.2.0, and release the new and improved one that you're working on for 2.2.1. This is primarily because I've got a lot of documentation-writing to do and won't be able to do thorough testing on this. I very much appreciate your work on this bit of the code.

I also have a suggestion for a new feature. Either as a command-line option or as an automatic feature during interactive processing, it would be great if the script could scan the existing `models` directory for SD models it knows about (from `INITIAL_MODELS.yaml`). If it finds SD models that aren't in the config file, it should offer to add them. This will let people rebuild their `config.yaml` without having to ask the script to download the models and answer 'y' to each prompt.

2022-11-28 02:46 UTC, lstein commented
That being said, if I do have time I will try very hard to get this in. The improvements look very good.

2022-11-28 03:05 UTC, ebr commented
All sounds great to me. I actually might have a viable approach to handling the `.invokeai` config file location in a backwards-compatible manner, but certainly wouldn't want any of this to delay the release. If anything, that would give me more time to do some more refactoring and properly test the changes. But I'm aiming try to get the final fixes in tonight.

2022-11-28 04:48 UTC, ebr commented
I think I was able to wrangle the config file location into a good state; this is now ready for review.

@lstein would you like me to tackle the auto-scanning of models in this same PR, or open a new feature request for it? I'd prefer the latter as it might get messy to review otherwise, but it's your call, please let me know.

2022-11-28 05:14 UTC, lstein commented
> I think I was able to wrangle the config file location into a good state; this is now ready for review.
> 
> @lstein would you like me to tackle the auto-scanning of models in this same PR, or open a new feature request for it? I'd prefer the latter as it might get messy to review otherwise, but it's your call, please let me know.

Go ahead and start a new PR. I'm going to integrate what you've done here with a few minor changes I made on a different branch and then merge.

2022-11-28 05:18 UTC, lstein approved these changes
Looking good. Will do some functional testing prior to merge.

2022-11-28 05:19 UTC, ebr commented
I seem to have oddly broken some tests, let me look into that :thinking:

2022-11-28 06:15 UTC, lstein requested changes
I started testing and then realized that the default location for the init file has become the InvokeAI repo. This is when neither --root nor INVOKEAI_ROOT is provided.

I don't really want the init file to be stored in the repo because ultimately I want to be able to do a non-source install. When this happens the repo is going to be hidden deep inside a venv folder somewhere and the user will never be able to find the init file. This is really tricky to finesse because the init file tells invoke where the root directory is, but if the init file is inside the root directory how does invoke find it?

In addition, the repo is really cluttered already.

So I want to consult with you about the design decision here. Maybe a better thing to do is to create the initfile in the user's home directory, don't make it hidden, and give clear instructions how they can move it by creating an environment variable or pointing invoke.py to it with --root each time. Sadly, users are not savvy about setting environment variables.

2022-11-28 06:30 UTC, ebr commented
> I started testing and then realized that the default location for the init file has become the InvokeAI repo.

That sounds unexpected and not intentional. The logic I was trying to implement was to: 1. if an existing config file is found in the user's home directory, then keep using it, and 2. if no existing file is found, then create one in the runtime directory. 

If the default location of the runtime directory happens to be with the root of the repo, then yes, this is a problem. I think this stems from: 

```diff
# This is usually overwritten by the command line and/or environment variables
- Globals.root = '.'
+ Globals.root = root_dir if (root_dir := os.getenv("INVOKEAI_ROOT")) else "."
```

But this behaviour should have remained unchanged if neither the env var nor the `--root_dir` are specified. I.e. `Globals.root` was already `"."` before this PR.

As far as I understand, we never want to mix the runtime dir and neither the cloned codebase nor especially the dev-installed Python module, as you mention. Would it make sense to instead default the runtime dir to be located at `~/invokeai/` instead of the more ambiguous `"."`?

2022-11-28 14:17 UTC, lstein commented
Yeah, I think we need to reverse the logic and have a predictable location of the `invokeai` directory rather than a predictable init file. The init file can then live inside `invokeai`.

2022-11-28 14:19 UTC, lstein commented
Just marking this as draft again while we work out the strategy.

2022-11-28 23:37 UTC, ebr commented
I also just noticed that the `configure_invokeai.py`, the initfile comments, and the CI tests all specify the `--root` option, while in `args.py`, `CLI.py` and elsewhere in the app we have `--root_dir`. 

@lstein perhaps leaving this PR unmerged until _after_ 2.2.0 is indeed for the best, so that we can clean it all up after the release dust settles. I will keep rebasing+updating it though. Do you agree?

(CLI argument handling and various entrypoints could use quite a bit of future refactoring + consolidation in general, IMHO)

2022-11-29 06:58 UTC, ebr commented
I moved the init file / root dir changes to another branch and will do a separate PR for it, as it was getting quite messy and needs a larger refactor.

2022-12-01 00:59 UTC, ebr commented
This is ready to be reviewed again, because the runtime dir / init file location refactoring will be dealt with separately, likely in https://github.com/invoke-ai/InvokeAI/pull/1615

2022-12-01 22:09 UTC, appinteractive commented
Very useful for installation via UI 🍾

2022-12-02 21:03 UTC, tildebyte approved these changes

2022-12-03 19:33 UTC, lstein approved these changes
This looks great. Thanks.

2022-12-03 19:33 UTC, merged