Save and display per-token attention maps
invoke-ai/InvokeAI pull request #1866
Opened 2022-12-08 19:09 UTC by damian0815

This pull request enables the display of per-token attention maps after generating an image.

### Done: 
[x] Collect and return attention maps to generate.py
[x] Pass attention maps and tokens to webUI - currently pushed as `attentionMaps` (base64 image) and `tokens` fields on the object emitted to the webUI socket with `generationResult`

### Todo:
[ ] Display maps - @psychedelicious and/or @blessedcoolant will need your help on this part

2022-12-08 20:52 UTC, blessedcoolant commented
Generation error:  `AttributeError: 'CrossAttention' object has no attribute 'cached_mem_free_total'`

2022-12-10 10:29 UTC, damian0815 commented
this should be merged into main asap, even if that means frontend isn't using it. 

attention map collection is always-on in this PR but the memory/performance impact is negligible.

2022-12-10 10:50 UTC, psychedelicious commented on backend/invoke_ai_web_server.py
> +
```suggestion
"""
Converts an image into a base64 image dataURL.
"""

def image_to_dataURL(image: ImageType) -> str:
    buffered = io.BytesIO()
    image.save(buffered, format="PNG")
    image_base64 = "data:image/png;base64," + base64.b64encode(
        buffered.getvalue()
    ).decode("UTF-8")
    return image_base64


```

Just adding types here for clarity (I have imported the PIL Image type as ImageType).

2022-12-10 10:55 UTC, psychedelicious requested changes
1 simple change requested - adding types to util function. I haven't been consistent with this at all but I want to make an effort to add types whenever possible going forward.

This is not related to this particular PR, but we will need to save the attention map data somewhere besides just the gallery. The gallery images arrays are not persisted across reloads, and even if they were, resetting localstorage will of course clear them.

So we need to think about how to store them as metadata.

2022-12-10 11:16 UTC, psychedelicious approved these changes

2022-12-10 14:57 UTC, merged