fix documentation of huggingface cache location
invoke-ai/InvokeAI pull request #2430
Opened 2023-01-26 22:31 UTC by lstein

Fix changelog to indicate correct path to default huggingface cache directory.

2023-01-27 01:42 UTC, JPPhoto requested changes
It seems that `XDG_CACHE_HOME` is something that should be mentioned. The code first scans for `HF_HOME`, then falls back to `XDG_CACHE_HOME/huggingface`, then falls back to `ROOTDIR/models`.
https://github.com/invoke-ai/InvokeAI/blob/ea0a6ba622ebed92b8fe77af936fc46a86b252bf/ldm/invoke/globals.py#L84-L97

2023-01-27 20:42 UTC, JPPhoto commented
@lstein After looking more into XDG_CACHE_HOME based on the comment in `globals.py`, I think we should keep it in as it's used by HF as a fallback if HF_HOME isn't set. I updated `CHANGELOG.md` to explain this precedence and hopefully what I wrote makes sense. Take a look.

2023-01-30 02:22 UTC, lstein commented
This looks good to me. @JPPhoto you will need to change your review to Approve and then merge.

2023-01-30 02:30 UTC, JPPhoto approved these changes

2023-01-30 02:30 UTC, merged