Fix broken links
invoke-ai/InvokeAI pull request #2841
Opened 2023-03-01 04:48 UTC by candleshine

These two links go to 404 pages on github.  Updated to the correct documentation locations

2023-03-05 02:07 UTC, blessedcoolant approved these changes

2023-03-05 02:07 UTC, blessedcoolant commented
Thanks for catching these.

2023-03-05 02:09 UTC, blessedcoolant requested changes
Please rebase this against `main`. We don't do commits against `development` anymore.

2023-03-09 11:02 UTC, blessedcoolant commented
I tried to rebase this manually here but it's just too many changes. I'd recommend making the same tweaks on a new PR against `main`. Will merge it up then. Thank you.

2023-03-29 01:12 UTC, lstein commented
This seems like a dead PR. Any objection to my closing?

2023-04-05 21:39 UTC, closed without merging