Add support for yet another TI embedding format (main version)
invoke-ai/InvokeAI pull request #3050
Opened 2023-03-27 13:43 UTC by lstein

- This PR adds support for embedding files that contain a single key "emb_params". The only example I know of this format is the "EasyNegative" embedding on HuggingFace, but there are certainly others.

- This PR also adds support for loading embedding files that have been saved in safetensors format.

- It also cleans up the code so that the logic of probing for and selecting the right format parser is clear.

- This is the same as #3045, which is on the 2.3 branch.

2023-03-27 19:39 UTC, JPPhoto approved these changes

2023-03-27 19:39 UTC, JPPhoto commented on invokeai/backend/stable_diffusion/textual_inversion_manager.py
> +                if scan_result.infected_files == 1:
Should we be testing > 0?

2023-03-28 11:00 UTC, damian0815 requested changes

2023-03-29 01:00 UTC, lstein commented on invokeai/backend/stable_diffusion/textual_inversion_manager.py
> +        embedding_info["embedding"] = embedding
Thanks. I’ll implement option 1.

2023-03-29 01:02 UTC, lstein commented on invokeai/backend/stable_diffusion/textual_inversion_manager.py
> +                embedding_info["name"] = (
True. This seems to be a long-standing bug.  We don’t deal well with embeddings that have multiple tokens. I’ll have to change the upstream architecture to receive a list of the parsed dicts.

2023-03-30 02:25 UTC, lstein commented on invokeai/backend/stable_diffusion/textual_inversion_manager.py
> +        embedding_info["embedding"] = embedding
Implemented using a dataclass to hold parameters - much easier to read now and less redundant.

2023-03-30 02:25 UTC, lstein commented on invokeai/backend/stable_diffusion/textual_inversion_manager.py
> +                embedding_info["name"] = (
Fixed, although I have yet to see an embedding file with multiple tokens in the wild.

2023-03-30 10:25 UTC, damian0815 approved these changes
looks good - with a small nitpick, having read the last version of `textual_inversion_manager.py` i think `EmbeddingInfo` would better be named `ParsedEmbeddingInfo` and also its definition ought to go beneath `TextualInversionInfo` - or better, it ought to be a subclass of `TextualInversionManager` itself (can't recall if that works in python). otherwise its scope/purpose is a little unclear.

2023-03-31 07:57 UTC, lstein commented on invokeai/backend/stable_diffusion/textual_inversion_manager.py
> +                if scan_result.infected_files == 1:
yes. fixed

2023-03-31 07:57 UTC, merged