Update dependencies
invoke-ai/InvokeAI pull request #3353
Opened 2023-05-07 02:36 UTC by lstein

# Resolve non-deterministic behavior when using `xformers`

This PR updates torch to 2.0.0 and xformers to 0.19. Together these seem to fix the non-deterministic behavior of image generation and I didn't observe any issues on my Linux system. Please evaluate on Windows 10 and Macintosh.

This PR also fixes the documentation for LoRAS, which is giving a 404 error right now, and bumps the version number up to 2.3.5.post1.

2023-05-07 03:09 UTC, JPPhoto approved these changes
Didn't test but these changes all look good.

2023-05-07 04:44 UTC, blessedcoolant approved these changes

2023-05-07 09:44 UTC, blessedcoolant approved these changes

2023-05-10 04:20 UTC, ebr approved these changes
:+1:

2023-05-16 19:45 UTC, GreggHelt2 requested changes
Tested starting from scratch with a manual install. 
Tested with `invokeai --web` and `invokeai --no-xformers--web`. Comparing multiple runs with xformers, without xformers and all params frozen, they all look identical to me. So deterministic image generation appears to be working!

The only issue I had was that specifying `--no-xformers` in invokeai.init seems to get ignored, or at least on startup xformers is reported as enabled:

> xformers memory-efficient attention is available and **enabled**

Whereas if I specify on command line `invokeai --no-xformers--web` xformers is reported as disabled:

> xformers memory-efficient attention is available but **disabled**

Is invokeai.init still a valid place to specify --no-xformers?

2023-05-16 20:14 UTC, GreggHelt2 approved these changes

2023-05-17 03:45 UTC, merged