Branch for 3.0alpha release installation tweaks and bug fixes
invoke-ai/InvokeAI pull request #3608
Opened 2023-06-28 21:48 UTC by lstein

This is a draft PR for accumulating bug fixes identified during the 3.0 alpha release phase.

2023-06-29 05:04 UTC, mickr777 commented
@lstein
is this a typo?
line 329  `vae_path = 'models/core/convert/se-vae-ft-mse'` in migrate_to_3.py

2023-07-01 23:49 UTC, psychedelicious requested changes

2023-07-01 23:49 UTC, psychedelicious commented on invokeai/frontend/web/package.json
I don't think there should be any changes to this file. What is the `linters` package for and why were the other package versions bumped? 

If it was accidental, please roll back the changes to `package.json`, re-run `yarn install` to update `yarn.lock` and then re-build the frontend with `yarn vite build`

2023-07-02 00:00 UTC, lstein commented on invokeai/frontend/web/package.json
Husky pre-commit command has been failing for me and is giving the errors shown below. I thought it might be because a package was missing and I started using `yarn add` to add suspected missing node modules. I had no idea it affects `package.json`

```
> @invoke-ai/invoke-ai-ui@0.0.1 lint-staged
> lint-staged

Could not parse lint-staged config.

✖ Validation Error:

  Invalid value for 'linters': { '*.{ts,tsx,js,json,md}': [ 'prettier --write', 'git add' ] }

  Advanced configuration has been deprecated.
```

2023-07-02 00:05 UTC, lstein commented on invokeai/frontend/web/package.json
Anyway, package.json has been rolled back.

2023-07-02 00:07 UTC, psychedelicious commented on invokeai/frontend/web/package.json
Ya yarn add kinda rolls on to those other systems. Not sure what's up with the pre-commit hook, I'll have a look

2023-07-07 18:22 UTC, blessedcoolant requested changes

2023-07-07 18:22 UTC, blessedcoolant commented on invokeai/frontend/web/package.json
> +    "@apidevtools/swagger-parser": "^10.1.0",
No longer being used? @psychedelicious

2023-07-07 18:22 UTC, blessedcoolant commented on invokeai/frontend/web/package.json
> +    "vite-plugin-node-polyfills": "^0.9.0",
Same with this.

2023-07-07 18:28 UTC, blessedcoolant approved these changes

2023-07-07 21:09 UTC, merged