model installer -- Prevent crashes on malformed models
invoke-ai/InvokeAI pull request #3619
Opened 2023-07-01 18:34 UTC by lstein

This small patch improves the stability of `invokeai-*` scripts by avoiding crashes in the model manager while scanning the models directory for new and removed models.

2023-07-01 23:51 UTC, psychedelicious requested changes

2023-07-01 23:51 UTC, psychedelicious commented on invokeai/frontend/web/package.json
Same comment as on #3608 regarding what I suspect are accidental changes to `package.json`

2023-07-02 00:07 UTC, lstein commented on invokeai/frontend/web/package.json
Rolled back.

2023-07-03 18:10 UTC, lstein commented
@psychedelicious I've made the requested change to rollback packages.json.

2023-07-04 15:27 UTC, psychedelicious commented
@lstein sorry but `yarn.lock` is still in this PR, can you please remove it

2023-07-04 15:28 UTC, psychedelicious approved these changes
I'm approving but please remove `yarn.lock` before merging

2023-07-17 21:11 UTC, merged