Don't unload models from GPU until the space is needed
invoke-ai/InvokeAI pull request #3713
Opened 2023-07-09 18:29 UTC by lstein

This PR keeps all models in GPU until space starts running low, at which point models will be offloaded from GPU to CPU starting with the smallest ones.

This should fix the 2-3s delay at the start of generations, but will tend to hog VRAM, potentially starving other programs of GPU resources. If this turns into a problem, we can add a high water mark that reserves a certain amount of VRAM for other uses.

2023-07-10 05:09 UTC, blessedcoolant approved these changes

2023-07-10 15:22 UTC, ebr requested changes

2023-07-10 15:22 UTC, ebr commented on invokeai/app/services/config.py
> +    reserve_gpu_mem: 1
```suggestion
    gpu_mem_reserved: 1
```

2023-07-11 20:23 UTC, lstein commented
Obsoleted by beta merge.

2023-07-11 20:23 UTC, closed without merging