dep(diffusers): upgrade diffusers to 0.20
invoke-ai/InvokeAI pull request #4311
Opened 2023-08-17 20:48 UTC by keturn

This allows us to work with some new stuff including TAESD: https://github.com/huggingface/diffusers/releases/tag/v0.20.0

Removed `is_safetensors_available` as safetensors is now a required dependency of diffusers.

## What type of PR is this? (check all applicable)

- dependency upgrade

## QA Instructions, Screenshots, Recordings

## Added/updated tests?

- no; only minimal code changes on our side, nothing new to test.

2023-08-17 20:56 UTC, hipsterusername approved these changes

2023-08-17 21:17 UTC, keturn commented
I did a quick test on Linux + xformers of generation stuff for SD 1.x, 2.x, and SDXL, and some inpainting, and that all seemed fine.

2023-08-18 01:19 UTC, blessedcoolant approved these changes

2023-08-18 01:42 UTC, GreggHelt2 requested changes
There is still code in backend/model_management/convert_ckpt_to_diffusers that uses the diffusers is_safetensors_available() method. I'm guessing those will currently break model manager when conversion to diffusers is needed.

2023-08-19 00:24 UTC, GreggHelt2 approved these changes
LGTM

2023-08-19 01:22 UTC, merged