Added extra steps to update the Cudnnn DLL found in the Torch packages
invoke-ai/InvokeAI pull request #4459
Opened 2023-09-05 04:54 UTC by Keerigan45

I added extra steps to update the Cudnnn DLL found in the Torch package because it wasn't optimised or didn't use the lastest version. So manually updating it can speed up iteration but the result might differ from each card. Exemple i passed from 3 it/s to a steady 20 it/s.

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [ ] No

## Description

## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

## [optional] Are there any post deployment tasks we need to perform?

2023-09-05 15:37 UTC, Malrama commented
Maybe also add if one should download the CUDA 11.X or CUDA 12.X version of CUDNN because that is something one is asked to choose from before downloading.
I assumed it was CUDA 11.X, am I correct?

2023-09-05 20:53 UTC, Keerigan45 commented
https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html May add this link and ask to just download the 11x version if their architecture doesn't show up. Or they can try both if they got time to see which version works better.

2023-09-06 04:01 UTC, Millu approved these changes
Fixed some types and updated readability, looks good to me!

2023-09-06 04:02 UTC, Millu requested changes

2023-09-06 04:02 UTC, Millu commented on docs/installation/030_INSTALL_CUDA_AND_ROCM.md
> +8. Go to https://developer.nvidia.com/cudnn
Add the link to 11.x/12.x

2023-09-07 03:17 UTC, Millu approved these changes
Looks great, thank you for adding this!

2023-09-07 03:38 UTC, merged