fix: Always use bbox bounds for Controlnet Image (canvas)
invoke-ai/InvokeAI pull request #4709
Opened 2023-09-26 22:33 UTC by blessedcoolant

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [ ] No

## Description

## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

## [optional] Are there any post deployment tasks we need to perform?

2023-09-26 22:45 UTC, psychedelicious approved these changes

2023-09-27 00:14 UTC, psychedelicious requested changes
Works as expected, but there's a side-quirk. If I set the bbox to include transparent area, that gets cropped out.

![image](https://github.com/invoke-ai/InvokeAI/assets/4822129/0923a2a6-0a4f-4bc8-b995-1a08e11cc571)

(beautiful work I know)

It crops the resultant image to the area that actually has pixels. That gives me this control image:
![image](https://github.com/invoke-ai/InvokeAI/assets/4822129/dd44f969-26e2-45ef-b89e-60a9843bc5c9)

This is a setting on the upload image route - we can tell it to crop visible or not.

I think for canvas to controlnet, we do not want to crop visible - does that make sense?

2023-09-27 00:16 UTC, blessedcoolant commented
Ah yeah. No cropping visible for ControlNet. Let me find it.

2023-09-27 02:23 UTC, psychedelicious approved these changes

2023-09-27 02:25 UTC, merged