#4700 Seed Input Fields for RandomInt and RandomFloat
invoke-ai/InvokeAI pull request #4748
Opened 2023-10-01 07:24 UTC by glibesyck

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [x] No

## Description

RandomInt and RandomFloat Nodes now have seed input field for reproducible workflows.

## Related Tickets & Documents

closes #4700 
relates to #4581

2023-10-02 05:42 UTC, Millu commented
Thanks for adding the seeds! 

As I was testing this, realized with a seed field in the RNG nodes, there's no easy way to have random generations via workflows now, unless a user manually changes the seed after Invoke-ing each time. 

Some options after discussing with @psychedelicious 
* Adopt a a seed modification system similar to Comfy
* "Random Seed" node - would have CPU / GPU option (it's seeds all the way down)
*  Remove seed option from RNG nodes and embed seed in image metadata graph for reproducibility 
* Move seed generation to the backend to function the same across Linear UI & workflows

Would love to get your thoughts @glibesyck!

2023-10-02 07:17 UTC, glibesyck commented
Thank you for the comments and discussion @Millu!
Great, I will give it a look at how Comfy reaches the desired functionality and return back;)

2023-10-02 17:20 UTC, glibesyck commented
After some research time, it seems to me that keeping seed value in image metadata is the most natural way for user to look for these values and fix them if needed. I've found the similar issue #4495 which addresses this question from more generalized perspective, including this one as well. I'm not sure whether I'm able to assist in development for this one, still it seems to me that it is indeed the great way to account for reproducibility.

2023-10-04 07:34 UTC, psychedelicious requested changes
Thanks for working on this @glibesyck !

The actual code changes here are fine I think, but this would be a breaking change as implemented. We'll need the seeded RNG to be opt-in, so the previous behaviour is not altered. That could be behind a boolean field.

Note that fields with "direct" input - like a number input on the UI - will never be `None`. Even if you set the seed field to `Optional[int] = InputField(default=None...`, the node would *always* get an integer. So whether or not the RNG is seeded cannot depend on the seed value itself, it *must* be a separate boolean field.

2023-10-04 07:34 UTC, psychedelicious commented on invokeai/app/invocations/math.py
> +    seed: int = InputField(default=None, ge=0, le=SEED_MAX, description=FieldDescriptions.seed_random_generation)
This should have a default value of a number (probably zero)

2023-10-04 07:34 UTC, psychedelicious commented on invokeai/app/invocations/math.py
> +    seed: int = InputField(default=None, ge=0, le=SEED_MAX, description=FieldDescriptions.seed_random_generation)
Default value should be an int

2023-10-04 07:34 UTC, psychedelicious commented
This PR does raise a deeper issue for which the solution is not clear, and that's what @Millu was asking about. It's not so much a question of how the seed value should be stored, but how we introduce randomness to the graph.

I've added a comment with more details in #4700 in case you have any thoughts.

2023-11-03 04:47 UTC, Millu commented
@glibesyck thank you for your effort on this! Going to close this for now as it appears this will be address in an alternative method 

We appreciate your contributions and would love to continue to see them, especially if there are any other items of interest here: https://github.com/orgs/invoke-ai/projects/7/views/10

2023-11-03 04:47 UTC, closed without merging