(WIP) Undo redo workflow editor
invoke-ai/InvokeAI pull request #4759
Opened 2023-10-02 11:29 UTC by mickr777

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [ ] No

## Description
Just getting feedcback if this is the right approach

## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

## [optional] Are there any post deployment tasks we need to perform?

2023-10-04 06:41 UTC, psychedelicious requested changes
I've requested some changes, and implemented them all locally, but there are some deeper issues:
- Many things we need to have in undo history do not trigger new history entries. For example, node labels, adding nodes to workflow linear UI, node positions
- Some things change rapidly and we need logic to not flood the undo history, eg the position of nodes, node notes/labels
- Node selection state needs to be updated after every history change

I've started addressing these but running into a few weird behaviours that I'll need to spend some time investigating.

Thanks for getting this effort started. I'm happy to take it from here. I'll update this PR when I work on it next.

2023-10-04 06:42 UTC, psychedelicious commented
Converted to draft pending resolution of the other issues

2023-10-04 06:52 UTC, mickr777 commented
> Converted to draft pending resolution of the other issues

Ok, I did try what I could, but I will leave it in your hands now 😃

2023-10-06 05:50 UTC, mickr777 commented on invokeai/frontend/web/src/features/nodes/store/nodesPersistDenylist.ts
> +  'shouldColorEdges',
Just notice This is the wrong nodesPersistDenylist.ts it must of snuck in from a test I was doing

2023-10-06 05:53 UTC, mickr777 commented on invokeai/frontend/web/src/features/nodes/store/nodesPersistDenylist.ts
> +  'shouldColorEdges',
Just notice This is the wrong nodesPersistDenylist.ts it must of snuck in from a test I was doing

2023-12-02 08:09 UTC, closed without merging