Add resize modes to image resize node
invoke-ai/InvokeAI pull request #5026
Opened 2023-11-02 11:14 UTC by VeyDlin

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x ] Yes #5014
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [x ] No: I'm not sure if there is documentation for this to update it.

## Description
Add resize mode property to image resize node:

1. Fill: In this mode, the image is adjusted to completely fill the available space while maintaining its aspect ratio. This means the image may be cropped to fit the desired dimensions. The entire available space is covered, but some parts of the image may be cut off.

2. Stretch: In this mode, the image is forcibly stretched or squished to fit the specified dimensions, disregarding its original aspect ratio. This can lead to distortion of image as the aspect ratio is not maintained.

3. Fit: This mode ensures that the entire image fits within the specified dimensions, while maintaining its aspect ratio. The image is resized proportionally to fit entirely within the specified dimensions.

4. Center: In this mode, the image is centered within the specified dimensions without any scaling or cropping. If the original image is smaller than the specified dimensions, it will be displayed as is, with empty space around it.

5. Crop: This mode the image is not scaled to fit the specified dimensions. Instead, the original image is inserted into the available space while maintaining its original size. If the specified dimensions are smaller than the original image, part of the image will be cropped.

## Related Tickets & Documents
- Related Issue #5014
- Closes #5014

## QA Instructions, Screenshots, Recordings
When selecting the resizing mode the image should look as indicated in the description

## Added/updated tests?

- [ ] Yes
- [ x] No : I do not know how to do this

2023-11-03 03:57 UTC, Millu commented
Thanks for submitting! 

Should get a code owner review soon

cc: @hipsterusername @blessedcoolant @psychedelicious

2023-11-03 04:31 UTC, blessedcoolant approved these changes

2023-11-05 19:04 UTC, hipsterusername commented
Is the default behavior for this the same as the current resize? I think technically it's 'stretch' right now?

I have not tested this yet, but have some other questions around how it's _not_ allowing dynamic aspect ratio changes in the event that both Width/Height are passed into the resize node.

2023-11-06 02:33 UTC, psychedelicious requested changes
Brief review - need to properly review when I'm at the computer in a day or two.

1. It looks like this changes the default behavior of the node to fit. If I understand correctly, current behavior is equivalent to the stretch mode. 

This will break existing workflows. The default behavior should not change.

2. The helper methods need arg and return types.

3. Minor nit: The helper methods are defined inside the invoke method, though only one is used. I think these should be dedicated functions outside the node.

2024-02-05 23:26 UTC, psychedelicious commented
@VeyDlin Do you anticipate following up on this PR?

2024-04-03 05:58 UTC, psychedelicious commented
Closing due to inactivity

2024-04-03 05:58 UTC, closed without merging