Simplify docker compose setup
invoke-ai/InvokeAI pull request #5046
Opened 2023-11-06 21:42 UTC by Rubonnek

## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [x] Yes - https://github.com/invoke-ai/InvokeAI/pull/5007#discussion_r1378792615
- [ ] No, because: 

      
## Have you updated all relevant documentation?
- [x] Yes
- [ ] No

## Description

Simplify Docker image creation and execution to a single script that spins up the right service in the docker compose file.
## Related Tickets & Documents

- Depends on #5007

## QA Instructions, Screenshots, Recordings
N/A

## Added/updated tests?

- [ ] Yes
- [x] No : same tests should work.

## [optional] Are there any post deployment tasks we need to perform?

Not to my knowledge.

2023-11-06 21:47 UTC, hipsterusername commented
#5007 just merged 🖖

2023-11-08 05:52 UTC, ebr reviewed
Looks great - thanks so much for the contribution. Will test on an nvidia system and report back

2023-12-07 14:45 UTC, ebr requested changes
Really like the clever solution with YAML anchors!
However, this change breaks the use of standard `docker compose` commands, and we do have users relying on or preferring to use `docker compose` directly. Could we keep the default `docker-compose.yml` with NVIDIA gpu support (the "happy path" for most common use case), while using a `-f docker-compose-custom.yml` (or similar) argument in `run.sh`?
Open to other ideas too. Great work otherwise, thanks for contributing.

2023-12-07 14:45 UTC, ebr commented on docker/run.sh
> +    build_args=$(awk '$1 ~ /=[^$]/ {print "--build-arg " $0 " "}' .env) &&
This should avoid commented lines in `.env` - prevents `--build-arg #SOME_VAR=foo`

```suggestion
    build_args=$(awk '$1 ~ /=[^$]/ && $0 !~ /^#/ {print "--build-arg " $0 " "}' .env) &&
```

2023-12-07 15:05 UTC, ebr commented on docker/run.sh
> +    service_name="invokeai-$(awk -F '=' '/GPU_DRIVER/ {print $2}' .env)"
if `GPU_DRIVER` isn't set in `.env`, we get `service_name=invokeai-` here

2023-12-07 18:27 UTC, ebr commented
@Rubonnek works great! TIL about `docker-compose` profiles. Awesome stuff, LGTM

2023-12-07 18:27 UTC, ebr approved these changes
Great work :100:

2023-12-14 04:23 UTC, hipsterusername approved these changes

2023-12-17 06:10 UTC, merged