first string only to test
invoke-ai/InvokeAI pull request #5096
Opened 2023-11-14 21:19 UTC by rohinish404

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [X] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [ ] No

## Description
This pr is still under development.

## Related Tickets & Documents

- Related Issue #5015
- Closes #5015

## QA Instructions, Screenshots, Recordings

## Added/updated tests?

- [ ] Yes
- [X] No : _please replace this line with details on why tests
      have not been included_

## [optional] Are there any post deployment tasks we need to perform?

2023-11-19 07:29 UTC, rohinish404 commented
i tried my best to change all the strings mentioned in the issue still if there's some left please let me know! :)

2023-11-19 14:17 UTC, hipsterusername commented
Thanks for your help!

2023-11-19 17:39 UTC, rohinish404 commented
> Thanks for your help!

Happy to help! :)

2023-11-19 17:41 UTC, rohinish404 commented
Making this pr again draft as new bugs have been found!

2023-11-19 21:59 UTC, psychedelicious requested changes
Requested one change.

Once that issue is fixed, let's get this merged, despite there being some untranslated strings in the app.

Then, I'll PR a change that will let us more effectively address all missing translations.

2023-11-19 21:59 UTC, psychedelicious commented on invokeai/frontend/web/src/features/modelManager/subpanels/AddModelsPanel/AdvancedAddModels.tsx
This needs to use the `useTranslation()` hook

2023-11-20 05:48 UTC, rohinish404 commented on invokeai/frontend/web/src/features/modelManager/subpanels/AddModelsPanel/AdvancedAddModels.tsx
resolved with latest commit

2023-11-20 06:22 UTC, psychedelicious approved these changes
Thanks @rohinish404!

2023-11-20 06:24 UTC, merged