[feature] Add probe for SDXL controlnet models
invoke-ai/InvokeAI pull request #5382
Opened 2024-01-02 22:54 UTC by lstein

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [X] Yes
- [ ] No, because:

      
## Have you updated all relevant documentation?
- [X] Yes
- [ ] No

## Description

This allows SDXL controlnet safetensors models to be auto probed and installed. However, the diffusers library does not yet know how to convert the SDXL models located at https://huggingface.co/lllyasviel/sd_control_collection, so further work needs to be done to make these models work with InvokeAI.

## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

## Merge Plan

Merge when approved.

## Added/updated tests?

- [ ] Yes
- [ ] No : _please replace this line with details on why tests
      have not been included_

## [optional] Are there any post deployment tasks we need to perform?

2024-01-03 13:54 UTC, RyanJDick requested changes
I tested with a couple of SDXL controlnets:
- [diffusers_xl_canny_full.safetensors](https://huggingface.co/lllyasviel/sd_control_collection/blob/main/diffusers_xl_canny_full.safetensors): Succeeded
- [diffusers_xl_canny_small.safetensors](https://huggingface.co/lllyasviel/sd_control_collection/blob/main/diffusers_xl_canny_small.safetensors): Failed (I assume this was supposed to work?)

2024-01-03 13:54 UTC, RyanJDick commented on invokeai/backend/model_management/model_probe.py
> +        raise InvalidModelException("{self.model_path}: Unable to determine base type")
This should be an f-string, and `self.model_path` does not exist:
```suggestion
        raise InvalidModelException(f"{self.checkpoint_path}: Unable to determine base type")
```

2024-01-03 13:54 UTC, RyanJDick commented on invokeai/backend/model_manager/probe.py
>          raise InvalidModelConfigException("{self.model_path}: Unable to determine base type")
```suggestion
        raise InvalidModelConfigException(f"{self.model_path}: Unable to determine base type")
```

2024-01-23 21:28 UTC, hipsterusername commented
@lstein - Does this need a re-review?

2024-03-18 00:50 UTC, lstein commented
@RyanJDick It should be correctly probing all SDXL controlnet models now.

2024-03-18 00:54 UTC, hipsterusername approved these changes

2024-03-21 14:49 UTC, merged