feat: :sparkles: disable/enable LorRas with a switch
invoke-ai/InvokeAI pull request #5591
Opened 2024-01-28 23:32 UTC by joshistoast

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [x] No, because:

      
## Have you updated all relevant documentation?
- [ ] Yes
- [x] No

## Description
Added an easy way to enable/disable LoRas within the ui. This is done by adding a switch next to the delete button, with logic that sets the weight to 0 when unchecked (disabled), and restoring the LoRa weight to it's last value when checked again (re-enabled).

## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings
![image](https://github.com/invoke-ai/InvokeAI/assets/23065423/82f3f6f8-0ed4-4052-aa76-be5068901d8f)

## Merge Plan

## Added/updated tests?

- [ ] Yes
- [x] No : I don't wanna

## [optional] Are there any post deployment tasks we need to perform?

2024-01-28 23:37 UTC, joshistoast commented
Increasing/decreasing the LoRa count badge would be neat, might change that later

2024-01-29 01:44 UTC, psychedelicious requested changes
Thanks Josh. This has a few issues:
1. If you disable a lora and refresh the page, the user-selected lora weight will be reset to zero, losing their setting
2. Due to the issue 1, the switch won't let you enable the lora again - the value in state is zero
3. The "disabled" loras will still be added to the graph (this is a pre-existing issue, loras with weight of 0 are added to the graph, it's just more of a problem when the concept of "disabling" is introduced to loras)

A better way to handle this would be to add `isEnabled` to the lora redux state.

2024-01-30 03:29 UTC, joshistoast commented
> Thanks Josh. This has a few issues:
> 
>     1. If you disable a lora and refresh the page, the user-selected lora weight will be reset to zero, losing their setting
> 
>     2. Due to the issue 1, the switch won't let you enable the lora again - the value in state is zero
> 
>     3. The "disabled" loras will still be added to the graph (this is a pre-existing issue, loras with weight of 0 are added to the graph, it's just more of a problem when the concept of "disabling" is introduced to loras)
> 
> 
> A better way to handle this would be to add `isEnabled` to the lora redux state.

Understood, I can use redux state to track that. However I feel like the first 2 can easily be fixed, and the existence of the lora within the graph shouldn't affect the generation if it's weight is 0 (unless for some reason it does).

2024-01-30 03:39 UTC, hipsterusername commented
> > Thanks Josh. This has a few issues:
> > ```
> > 1. If you disable a lora and refresh the page, the user-selected lora weight will be reset to zero, losing their setting
> > 
> > 2. Due to the issue 1, the switch won't let you enable the lora again - the value in state is zero
> > 
> > 3. The "disabled" loras will still be added to the graph (this is a pre-existing issue, loras with weight of 0 are added to the graph, it's just more of a problem when the concept of "disabling" is introduced to loras)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > A better way to handle this would be to add `isEnabled` to the lora redux state.
> 
> Understood, I can use redux state to track that. However I feel like the first 2 can easily be fixed, and the existence of the lora within the graph shouldn't affect the generation if it's weight is 0 (unless for some reason it does).

Think it’s generally going to be bad practice to leave nodes in a composed graph that shouldn’t be there. It creates potential for future bugs/issues to crop up with graph mutation

2024-01-30 05:50 UTC, joshistoast commented
@psychedelicious Where would I exclude disabled LoRas from the graph, given they now have a `disabled` flag that can be used?

2024-01-30 14:11 UTC, psychedelicious commented on invokeai/frontend/web/src/features/lora/store/loraSlice.ts
> +    loraToggle: (state, action: PayloadAction<{ id: string; disabled: boolean }>) => {
Another naming nitpick - it should be `loraToggled`, or `loraIsEnabledChanged`.

2024-01-30 14:18 UTC, psychedelicious commented on invokeai/frontend/web/src/features/settingsAccordions/components/GenerationSettingsAccordion/GenerationSettingsAccordion.tsx
>    if (generation.model) {
I'd prefer to not use an extra selector here - all we need is the count of enabled loras for the badge. So something like this is sufficient:

```ts
const enabledLoRAsCount = filter(lora.loras, (l) => l.isEnabled).length;
const loraTabBadges = enabledLoRAsCount ? [enabledLoRAsCount] : [];
```

2024-01-30 14:21 UTC, psychedelicious commented on invokeai/frontend/web/src/features/lora/components/LoRACard.tsx
Let's disable the weight slider and number input when the lora is disabled

2024-01-31 05:37 UTC, psychedelicious requested changes
Just a couple minor changes requested, ty

2024-01-31 05:37 UTC, psychedelicious commented on invokeai/frontend/web/src/features/nodes/util/graph/addLoRAsToGraph.ts
> +  // const { loras } = state.lora;
errant comment

2024-01-31 05:37 UTC, psychedelicious commented on invokeai/frontend/web/src/features/settingsAccordions/components/GenerationSettingsAccordion/GenerationSettingsAccordion.tsx
> +  const enabledLoRAsCount = filter(lora.loras, (l: LoRA) => !!l.isEnabled).length;
Doesn't need the `LoRA` type annotation here

2024-01-31 05:37 UTC, psychedelicious commented on invokeai/frontend/web/src/features/lora/store/loraSlice.ts
> +    },
"toggled" implies the new state will be the opposite of the previous state - so I'd expect "toggled" actions to not have an `isEnabled` boolean. `loraIsEnabledChanged` is clearer.

This is the establish project convention, used elsewhere, for ex:

```ts
    controlAdapterIsEnabledChanged: (state, action: PayloadAction<{ id: string; isEnabled: boolean }>) => {
    ...
    controlAdapterAutoConfigToggled: (state, action: PayloadAction<{ id: string }>) => {
```

2024-01-31 05:48 UTC, psychedelicious approved these changes
Thanks @joshistoast ! Nice UX win here.

2024-01-31 05:50 UTC, merged