Quick Seamless Fixes
invoke-ai/InvokeAI pull request #5685
Opened 2024-02-09 03:40 UTC by hipsterusername

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ X ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Community Node Submission

## Have you discussed this change with the InvokeAI team?
- [ ] Yes
- [ X ] No, because: It's small

      
## Have you updated all relevant documentation?
- [ ] Yes
- [ X ] No

## Description
This pulls out some of the updates from the WIP Seamless branch that has yet to be completed, and hardcodes values that are exposed in that branch. Given that seamless currently does not generate seamless textures, and this fix results in seamless outputs, it's an improvement even if it doesn't resolve this in a "perfect" way that exposes all variables to the end user.

better over perfect.

![f07b7e49-80c2-4659-bb36-d50ec80b1f8b](https://github.com/invoke-ai/InvokeAI/assets/31807370/36a40bd9-8fc4-41d5-bd1e-209fc828987e)

2024-02-09 07:58 UTC, psychedelicious approved these changes
Confirmed it works

2024-02-09 22:33 UTC, psychedelicious commented
@blessedcoolant what's actually happening here is a bit beyond me but it works, what do u think

2024-02-09 22:54 UTC, blessedcoolant requested changes

2024-02-09 22:54 UTC, blessedcoolant commented on invokeai/backend/model_management/seamless.py
> +        skip_conv2 = True
What's the point of these three vars? They're set to `0` and `True` always. They're not altered anywhere else in the function or pass into the function.

2024-02-09 22:54 UTC, blessedcoolant commented on invokeai/backend/model_management/seamless.py
> +                if resnet_num > 0 and skip_second_resnet:
When the above vars are removed, they can removed from here too.

2024-02-09 22:55 UTC, blessedcoolant commented
> @blessedcoolant what's actually happening here is a bit beyond me but it works, what do u think

Seems to me like its mostly a refactor. Has some unnecessary vars in it but the rest seems good.

2024-02-09 22:56 UTC, blessedcoolant commented on invokeai/backend/model_management/seamless.py
> +        skip_conv2 = True
Okay I see that it hardcodes vars from another branch. But I think you can just remove these from this PR and let the other branch actually take over when if and when it gets merged in.

2024-02-11 04:11 UTC, hipsterusername commented
@blessedcoolant - Merge this, or merge the other. This fixes the issue, and it's currently broken.

2024-02-11 04:57 UTC, blessedcoolant commented
@hipsterusername clean up the unused vars in this and merge it. Can worry about the other one (dunno which one) when it's ready.

2024-02-11 06:22 UTC, hipsterusername commented
feel free to update.

2024-02-11 06:23 UTC, hipsterusername commented
although, i'd actually do one thing - test the skipped layers and see which # you prefer. I'm not sure I actually landed on 0 being the best. might have been 1-2

2024-02-11 08:12 UTC, blessedcoolant commented
> although, i'd actually do one thing - test the skipped layers and see which # you prefer. I'm not sure I actually landed on 0 being the best. might have been 1-2

Does this need to be exposed or can we hardcode?

2024-02-13 02:34 UTC, psychedelicious commented
I cleaned up the unused stuff

2024-02-13 17:32 UTC, blessedcoolant approved these changes

2024-02-13 18:08 UTC, merged