feat: Unified Canvas Fit Image Size on Drop
invoke-ai/InvokeAI pull request #6136
Opened 2024-04-04 11:21 UTC by symant233

## Summary

**Feature (Unified Canvas):** This PR add an option `shouldFitImageSize` to `IAICanvasToolbar` settings, which control the inital `boundingBoxDimensions` to fit initial image size.

## Related Issues / Discussions

## QA Instructions

Switch to Unified Canvas tab, drag and drop an image. When the `shouldFitImageSize` is checked from top toolbar settings, the inital bounding box size will fit to image.

## Merge Plan

## Checklist

- [x] _The PR has a short but descriptive title, suitable for a changelog_
- [ ] _Tests added / updated (if applicable)_
- [ ] _Documentation added / updated (if applicable)_

2024-04-04 11:40 UTC, psychedelicious requested changes
Thanks! I like this feature. I've requested 2 small changes.

2024-04-04 11:40 UTC, psychedelicious commented on invokeai/frontend/web/src/features/canvas/store/canvasSlice.ts
> +          ? { width, height }
We'll need to use `roundDownToMultiple` on both width and height in case the input images don't have dimensions that are a multiple of 8.

2024-04-04 11:40 UTC, psychedelicious commented on invokeai/frontend/web/public/locales/zh_CN.json
Thanks for translating - but we do the translations via weblate: https://invoke-ai.github.io/InvokeAI/contributing/contribution_guides/translation/

We should only update `en.json` in the repo, then translate on weblate, and it will PR the new translations to the repo

2024-04-04 12:05 UTC, hipsterusername requested changes

2024-04-04 12:05 UTC, hipsterusername commented on invokeai/frontend/web/src/features/canvas/components/IAICanvasToolbar/IAICanvasSettingsButtonPopover.tsx
> +  const handleChangeSholdFitImageSize = useCallback(
“Should”

2024-04-04 12:05 UTC, hipsterusername commented on invokeai/frontend/web/src/features/canvas/components/IAICanvasToolbar/IAICanvasSettingsButtonPopover.tsx
> +                <Checkbox isChecked={sholdFitImageSize} onChange={handleChangeSholdFitImageSize} />
Should*

2024-04-04 12:05 UTC, hipsterusername commented on invokeai/frontend/web/src/features/canvas/store/canvasSlice.ts
> +  shouldFitImageSize: false,
Seems like this should default to true?

2024-04-04 12:06 UTC, psychedelicious approved these changes
Looks good, thanks!

Just to clarify for users or other contributors - this setting only changes the behaviour when the canvas image you import is larger than the optimal dimension of the selected model.

2024-04-04 12:06 UTC, hipsterusername commented on invokeai/frontend/web/src/features/canvas/store/canvasSlice.ts
> +  shouldFitImageSize: false,
(Open to discussion - like the idea, seems like most people would want it)

2024-04-04 12:06 UTC, hipsterusername commented
- Would users ever not want this? I.e., could it just be the default?

> Looks good, thanks!
> 
> Just to clarify for users or other contributors - this setting only changes the behaviour when the canvas image you import is larger than the optimal dimension of the selected model.

Ah. I see.

2024-04-04 20:50 UTC, psychedelicious commented
@hipsterusername Can you please re-review?

2024-04-05 03:14 UTC, hipsterusername approved these changes

2024-04-05 03:14 UTC, hipsterusername commented
🚀

2024-04-05 04:23 UTC, merged