Creation of Videos help document
invoke-ai/InvokeAI pull request #6235
Opened 2024-04-17 21:17 UTC by sarashinai

## Summary

I have created a VIDEOS.md file in the help directory with a curated and annotated list of all the Invoke YouTube videos. The purpose is for the videos to be integrated into Invokes web presence and to make finding specific content easier.

## Related Issues / Discussions

## QA Instructions

## Merge Plan

## Checklist

- [ X ] _The PR has a short but descriptive title, suitable for a changelog_
- [ ] _Tests added / updated (if applicable)_
- [ X ] _Documentation added / updated (if applicable)_

2024-04-25 15:22 UTC, hipsterusername approved these changes
This is awesome!!

2024-04-25 15:22 UTC, hipsterusername commented on docs/features/GALLERY.md
> +## Acknowledgements
We can probably remove this section - it’s a tad outdated now!

2026-04-26 19:03 UTC, lstein requested changes
Flagging this to be updated and integrated into the documentation. One of the team members will take a look at it.

2026-07-01 19:21 UTC, lstein approved these changes
Thank you for the contribution. It was a long time getting merged in because we changed our doc system in the interim.

2026-07-01 19:21 UTC, merged